version: '3.3'

services:
  mikrotik:
    image: cnsoluciones/mikrotik:latest
    container_name: mikrotik
    restart: always
    ports:
      - 21:21
      - 22:22
      - 23:23
      - 50:50
      - 51:51
      - 80:80
      - 443:443
      - 500:500
      - 1194:1194
      - 1701:1701
      - 1723:1723
      - 4500:4500
      - 5900:5900
      - 8080:8080
      - 8291:8291
      - 8728:8728
      - 8729:8729
    environment:
      - VNCPASSWORD=false
    network_mode: bridge
    privileged: true

  winbox:
    image: cnsoluciones/novnc-winbox:latest
    container_name: winbox
    hostname: winbox
    restart: always
    volumes:
      - ./wine:/home/alpine/.wine
    links:
      - mikrotik
    ports:
      - 5901:5900
      - 18081:8080
    network_mode: bridge
